--- arch/arm/mach-msm/qdsp6/Makefile
+++ arch/arm/mach-msm/qdsp6/Makefile
@@ -7,5 +7,5 @@
 obj-y += audio_ctl.o
 obj-y += msm_q6vdec.o
 obj-y += msm_q6venc.o
-obj-y += aac_in.o
+obj-y += aac_in.o amrnb_in.o
 obj-y += qcelp_in.o
